version: "3.8"

volumes:
  pg_volume:
  pg_test_volume:

services:
  server-auth:
    container_name: server_auth
    build:
      dockerfile: HotReload.Dockerfile
    ports:
      - "11000:11000"
    restart: always
    volumes:
      - ./:/app
    networks:
      - banking-system

  server-air-auth:
    container_name: server_air_auth
    build:
      dockerfile: air.Dockerfile
    ports:
      - "11010:11010"
    restart: always
    volumes:
      - ./:/app
    networks:
      - banking-system

  server-auth-debug:
    container_name: server_auth_debug
    build:
      dockerfile: debug.Dockerfile
    ports:
      - "11001:11001"
      - "40001:40001"
    restart: always
    volumes:
      - ./:/app
    networks:
      - banking-system

  pg-auth:
    image: postgres:15-alpine3.18
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data
    networks:
      - banking-system

  pg-test-auth:
    image: postgres:15-alpine3.18
    environment:
      - "POSTGRES_DB=${PG_DB_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT_TEST}:5432"
    volumes:
      - pg_test_volume:/var/lib/postgresql/data
    networks:
      - banking-system

  redis-auth:
    image: redis
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - banking-system

networks:
  banking-system:
    name: banking-system
    external: true
