package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/patyukin/bs-auth/internal/repository.AuthRepository -o ./mocks/auth_repository_minimock.go -n AuthRepositoryMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// AuthRepositoryMock implements repository.AuthRepository
type AuthRepositoryMock struct {
	t minimock.Tester

	funcCreate          func(ctx context.Context, userId int64) (s1 string, err error)
	inspectFuncCreate   func(ctx context.Context, userId int64)
	afterCreateCounter  uint64
	beforeCreateCounter uint64
	CreateMock          mAuthRepositoryMockCreate
}

// NewAuthRepositoryMock returns a mock for repository.AuthRepository
func NewAuthRepositoryMock(t minimock.Tester) *AuthRepositoryMock {
	m := &AuthRepositoryMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateMock = mAuthRepositoryMockCreate{mock: m}
	m.CreateMock.callArgs = []*AuthRepositoryMockCreateParams{}

	return m
}

type mAuthRepositoryMockCreate struct {
	mock               *AuthRepositoryMock
	defaultExpectation *AuthRepositoryMockCreateExpectation
	expectations       []*AuthRepositoryMockCreateExpectation

	callArgs []*AuthRepositoryMockCreateParams
	mutex    sync.RWMutex
}

// AuthRepositoryMockCreateExpectation specifies expectation struct of the AuthRepository.Create
type AuthRepositoryMockCreateExpectation struct {
	mock    *AuthRepositoryMock
	params  *AuthRepositoryMockCreateParams
	results *AuthRepositoryMockCreateResults
	Counter uint64
}

// AuthRepositoryMockCreateParams contains parameters of the AuthRepository.Create
type AuthRepositoryMockCreateParams struct {
	ctx    context.Context
	userId int64
}

// AuthRepositoryMockCreateResults contains results of the AuthRepository.Create
type AuthRepositoryMockCreateResults struct {
	s1  string
	err error
}

// Expect sets up expected params for AuthRepository.Create
func (mmCreate *mAuthRepositoryMockCreate) Expect(ctx context.Context, userId int64) *mAuthRepositoryMockCreate {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuthRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AuthRepositoryMockCreateExpectation{}
	}

	mmCreate.defaultExpectation.params = &AuthRepositoryMockCreateParams{ctx, userId}
	for _, e := range mmCreate.expectations {
		if minimock.Equal(e.params, mmCreate.defaultExpectation.params) {
			mmCreate.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreate.defaultExpectation.params)
		}
	}

	return mmCreate
}

// Inspect accepts an inspector function that has same arguments as the AuthRepository.Create
func (mmCreate *mAuthRepositoryMockCreate) Inspect(f func(ctx context.Context, userId int64)) *mAuthRepositoryMockCreate {
	if mmCreate.mock.inspectFuncCreate != nil {
		mmCreate.mock.t.Fatalf("Inspect function is already set for AuthRepositoryMock.Create")
	}

	mmCreate.mock.inspectFuncCreate = f

	return mmCreate
}

// Return sets up results that will be returned by AuthRepository.Create
func (mmCreate *mAuthRepositoryMockCreate) Return(s1 string, err error) *AuthRepositoryMock {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuthRepositoryMock.Create mock is already set by Set")
	}

	if mmCreate.defaultExpectation == nil {
		mmCreate.defaultExpectation = &AuthRepositoryMockCreateExpectation{mock: mmCreate.mock}
	}
	mmCreate.defaultExpectation.results = &AuthRepositoryMockCreateResults{s1, err}
	return mmCreate.mock
}

// Set uses given function f to mock the AuthRepository.Create method
func (mmCreate *mAuthRepositoryMockCreate) Set(f func(ctx context.Context, userId int64) (s1 string, err error)) *AuthRepositoryMock {
	if mmCreate.defaultExpectation != nil {
		mmCreate.mock.t.Fatalf("Default expectation is already set for the AuthRepository.Create method")
	}

	if len(mmCreate.expectations) > 0 {
		mmCreate.mock.t.Fatalf("Some expectations are already set for the AuthRepository.Create method")
	}

	mmCreate.mock.funcCreate = f
	return mmCreate.mock
}

// When sets expectation for the AuthRepository.Create which will trigger the result defined by the following
// Then helper
func (mmCreate *mAuthRepositoryMockCreate) When(ctx context.Context, userId int64) *AuthRepositoryMockCreateExpectation {
	if mmCreate.mock.funcCreate != nil {
		mmCreate.mock.t.Fatalf("AuthRepositoryMock.Create mock is already set by Set")
	}

	expectation := &AuthRepositoryMockCreateExpectation{
		mock:   mmCreate.mock,
		params: &AuthRepositoryMockCreateParams{ctx, userId},
	}
	mmCreate.expectations = append(mmCreate.expectations, expectation)
	return expectation
}

// Then sets up AuthRepository.Create return parameters for the expectation previously defined by the When method
func (e *AuthRepositoryMockCreateExpectation) Then(s1 string, err error) *AuthRepositoryMock {
	e.results = &AuthRepositoryMockCreateResults{s1, err}
	return e.mock
}

// Create implements repository.AuthRepository
func (mmCreate *AuthRepositoryMock) Create(ctx context.Context, userId int64) (s1 string, err error) {
	mm_atomic.AddUint64(&mmCreate.beforeCreateCounter, 1)
	defer mm_atomic.AddUint64(&mmCreate.afterCreateCounter, 1)

	if mmCreate.inspectFuncCreate != nil {
		mmCreate.inspectFuncCreate(ctx, userId)
	}

	mm_params := &AuthRepositoryMockCreateParams{ctx, userId}

	// Record call args
	mmCreate.CreateMock.mutex.Lock()
	mmCreate.CreateMock.callArgs = append(mmCreate.CreateMock.callArgs, mm_params)
	mmCreate.CreateMock.mutex.Unlock()

	for _, e := range mmCreate.CreateMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.s1, e.results.err
		}
	}

	if mmCreate.CreateMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreate.CreateMock.defaultExpectation.Counter, 1)
		mm_want := mmCreate.CreateMock.defaultExpectation.params
		mm_got := AuthRepositoryMockCreateParams{ctx, userId}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreate.t.Errorf("AuthRepositoryMock.Create got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreate.CreateMock.defaultExpectation.results
		if mm_results == nil {
			mmCreate.t.Fatal("No results are set for the AuthRepositoryMock.Create")
		}
		return (*mm_results).s1, (*mm_results).err
	}
	if mmCreate.funcCreate != nil {
		return mmCreate.funcCreate(ctx, userId)
	}
	mmCreate.t.Fatalf("Unexpected call to AuthRepositoryMock.Create. %v %v", ctx, userId)
	return
}

// CreateAfterCounter returns a count of finished AuthRepositoryMock.Create invocations
func (mmCreate *AuthRepositoryMock) CreateAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.afterCreateCounter)
}

// CreateBeforeCounter returns a count of AuthRepositoryMock.Create invocations
func (mmCreate *AuthRepositoryMock) CreateBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreate.beforeCreateCounter)
}

// Calls returns a list of arguments used in each call to AuthRepositoryMock.Create.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreate *mAuthRepositoryMockCreate) Calls() []*AuthRepositoryMockCreateParams {
	mmCreate.mutex.RLock()

	argCopy := make([]*AuthRepositoryMockCreateParams, len(mmCreate.callArgs))
	copy(argCopy, mmCreate.callArgs)

	mmCreate.mutex.RUnlock()

	return argCopy
}

// MinimockCreateDone returns true if the count of the Create invocations corresponds
// the number of defined expectations
func (m *AuthRepositoryMock) MinimockCreateDone() bool {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		return false
	}
	return true
}

// MinimockCreateInspect logs each unmet expectation
func (m *AuthRepositoryMock) MinimockCreateInspect() {
	for _, e := range m.CreateMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthRepositoryMock.Create with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.CreateMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		if m.CreateMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to AuthRepositoryMock.Create")
		} else {
			m.t.Errorf("Expected call to AuthRepositoryMock.Create with params: %#v", *m.CreateMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreate != nil && mm_atomic.LoadUint64(&m.afterCreateCounter) < 1 {
		m.t.Error("Expected call to AuthRepositoryMock.Create")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthRepositoryMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockCreateInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateDone()
}
