package mocks

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i github.com/patyukin/bs-auth/internal/service.AuthService -o ./mocks/auth_service_minimock.go -n AuthServiceMock

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
	"github.com/patyukin/bs-auth/internal/model"
	desc "github.com/patyukin/bs-auth/pkg/auth_v1"
)

// AuthServiceMock implements service.AuthService
type AuthServiceMock struct {
	t minimock.Tester

	funcSignIn          func(ctx context.Context, params *model.User) (ap1 *desc.AuthResponse, err error)
	inspectFuncSignIn   func(ctx context.Context, params *model.User)
	afterSignInCounter  uint64
	beforeSignInCounter uint64
	SignInMock          mAuthServiceMockSignIn
}

// NewAuthServiceMock returns a mock for service.AuthService
func NewAuthServiceMock(t minimock.Tester) *AuthServiceMock {
	m := &AuthServiceMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.SignInMock = mAuthServiceMockSignIn{mock: m}
	m.SignInMock.callArgs = []*AuthServiceMockSignInParams{}

	return m
}

type mAuthServiceMockSignIn struct {
	mock               *AuthServiceMock
	defaultExpectation *AuthServiceMockSignInExpectation
	expectations       []*AuthServiceMockSignInExpectation

	callArgs []*AuthServiceMockSignInParams
	mutex    sync.RWMutex
}

// AuthServiceMockSignInExpectation specifies expectation struct of the AuthService.SignIn
type AuthServiceMockSignInExpectation struct {
	mock    *AuthServiceMock
	params  *AuthServiceMockSignInParams
	results *AuthServiceMockSignInResults
	Counter uint64
}

// AuthServiceMockSignInParams contains parameters of the AuthService.SignIn
type AuthServiceMockSignInParams struct {
	ctx    context.Context
	params *model.User
}

// AuthServiceMockSignInResults contains results of the AuthService.SignIn
type AuthServiceMockSignInResults struct {
	ap1 *desc.AuthResponse
	err error
}

// Expect sets up expected params for AuthService.SignIn
func (mmSignIn *mAuthServiceMockSignIn) Expect(ctx context.Context, params *model.User) *mAuthServiceMockSignIn {
	if mmSignIn.mock.funcSignIn != nil {
		mmSignIn.mock.t.Fatalf("AuthServiceMock.SignIn mock is already set by Set")
	}

	if mmSignIn.defaultExpectation == nil {
		mmSignIn.defaultExpectation = &AuthServiceMockSignInExpectation{}
	}

	mmSignIn.defaultExpectation.params = &AuthServiceMockSignInParams{ctx, params}
	for _, e := range mmSignIn.expectations {
		if minimock.Equal(e.params, mmSignIn.defaultExpectation.params) {
			mmSignIn.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmSignIn.defaultExpectation.params)
		}
	}

	return mmSignIn
}

// Inspect accepts an inspector function that has same arguments as the AuthService.SignIn
func (mmSignIn *mAuthServiceMockSignIn) Inspect(f func(ctx context.Context, params *model.User)) *mAuthServiceMockSignIn {
	if mmSignIn.mock.inspectFuncSignIn != nil {
		mmSignIn.mock.t.Fatalf("Inspect function is already set for AuthServiceMock.SignIn")
	}

	mmSignIn.mock.inspectFuncSignIn = f

	return mmSignIn
}

// Return sets up results that will be returned by AuthService.SignIn
func (mmSignIn *mAuthServiceMockSignIn) Return(ap1 *desc.AuthResponse, err error) *AuthServiceMock {
	if mmSignIn.mock.funcSignIn != nil {
		mmSignIn.mock.t.Fatalf("AuthServiceMock.SignIn mock is already set by Set")
	}

	if mmSignIn.defaultExpectation == nil {
		mmSignIn.defaultExpectation = &AuthServiceMockSignInExpectation{mock: mmSignIn.mock}
	}
	mmSignIn.defaultExpectation.results = &AuthServiceMockSignInResults{ap1, err}
	return mmSignIn.mock
}

// Set uses given function f to mock the AuthService.SignIn method
func (mmSignIn *mAuthServiceMockSignIn) Set(f func(ctx context.Context, params *model.User) (ap1 *desc.AuthResponse, err error)) *AuthServiceMock {
	if mmSignIn.defaultExpectation != nil {
		mmSignIn.mock.t.Fatalf("Default expectation is already set for the AuthService.SignIn method")
	}

	if len(mmSignIn.expectations) > 0 {
		mmSignIn.mock.t.Fatalf("Some expectations are already set for the AuthService.SignIn method")
	}

	mmSignIn.mock.funcSignIn = f
	return mmSignIn.mock
}

// When sets expectation for the AuthService.SignIn which will trigger the result defined by the following
// Then helper
func (mmSignIn *mAuthServiceMockSignIn) When(ctx context.Context, params *model.User) *AuthServiceMockSignInExpectation {
	if mmSignIn.mock.funcSignIn != nil {
		mmSignIn.mock.t.Fatalf("AuthServiceMock.SignIn mock is already set by Set")
	}

	expectation := &AuthServiceMockSignInExpectation{
		mock:   mmSignIn.mock,
		params: &AuthServiceMockSignInParams{ctx, params},
	}
	mmSignIn.expectations = append(mmSignIn.expectations, expectation)
	return expectation
}

// Then sets up AuthService.SignIn return parameters for the expectation previously defined by the When method
func (e *AuthServiceMockSignInExpectation) Then(ap1 *desc.AuthResponse, err error) *AuthServiceMock {
	e.results = &AuthServiceMockSignInResults{ap1, err}
	return e.mock
}

// SignIn implements service.AuthService
func (mmSignIn *AuthServiceMock) SignIn(ctx context.Context, params *model.User) (ap1 *desc.AuthResponse, err error) {
	mm_atomic.AddUint64(&mmSignIn.beforeSignInCounter, 1)
	defer mm_atomic.AddUint64(&mmSignIn.afterSignInCounter, 1)

	if mmSignIn.inspectFuncSignIn != nil {
		mmSignIn.inspectFuncSignIn(ctx, params)
	}

	mm_params := &AuthServiceMockSignInParams{ctx, params}

	// Record call args
	mmSignIn.SignInMock.mutex.Lock()
	mmSignIn.SignInMock.callArgs = append(mmSignIn.SignInMock.callArgs, mm_params)
	mmSignIn.SignInMock.mutex.Unlock()

	for _, e := range mmSignIn.SignInMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.ap1, e.results.err
		}
	}

	if mmSignIn.SignInMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmSignIn.SignInMock.defaultExpectation.Counter, 1)
		mm_want := mmSignIn.SignInMock.defaultExpectation.params
		mm_got := AuthServiceMockSignInParams{ctx, params}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmSignIn.t.Errorf("AuthServiceMock.SignIn got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmSignIn.SignInMock.defaultExpectation.results
		if mm_results == nil {
			mmSignIn.t.Fatal("No results are set for the AuthServiceMock.SignIn")
		}
		return (*mm_results).ap1, (*mm_results).err
	}
	if mmSignIn.funcSignIn != nil {
		return mmSignIn.funcSignIn(ctx, params)
	}
	mmSignIn.t.Fatalf("Unexpected call to AuthServiceMock.SignIn. %v %v", ctx, params)
	return
}

// SignInAfterCounter returns a count of finished AuthServiceMock.SignIn invocations
func (mmSignIn *AuthServiceMock) SignInAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignIn.afterSignInCounter)
}

// SignInBeforeCounter returns a count of AuthServiceMock.SignIn invocations
func (mmSignIn *AuthServiceMock) SignInBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmSignIn.beforeSignInCounter)
}

// Calls returns a list of arguments used in each call to AuthServiceMock.SignIn.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmSignIn *mAuthServiceMockSignIn) Calls() []*AuthServiceMockSignInParams {
	mmSignIn.mutex.RLock()

	argCopy := make([]*AuthServiceMockSignInParams, len(mmSignIn.callArgs))
	copy(argCopy, mmSignIn.callArgs)

	mmSignIn.mutex.RUnlock()

	return argCopy
}

// MinimockSignInDone returns true if the count of the SignIn invocations corresponds
// the number of defined expectations
func (m *AuthServiceMock) MinimockSignInDone() bool {
	for _, e := range m.SignInMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SignInMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSignInCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSignIn != nil && mm_atomic.LoadUint64(&m.afterSignInCounter) < 1 {
		return false
	}
	return true
}

// MinimockSignInInspect logs each unmet expectation
func (m *AuthServiceMock) MinimockSignInInspect() {
	for _, e := range m.SignInMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to AuthServiceMock.SignIn with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.SignInMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterSignInCounter) < 1 {
		if m.SignInMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to AuthServiceMock.SignIn")
		} else {
			m.t.Errorf("Expected call to AuthServiceMock.SignIn with params: %#v", *m.SignInMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcSignIn != nil && mm_atomic.LoadUint64(&m.afterSignInCounter) < 1 {
		m.t.Error("Expected call to AuthServiceMock.SignIn")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *AuthServiceMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockSignInInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *AuthServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *AuthServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockSignInDone()
}
